export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGOUT = 'LOGOUT';
export const SOCIAL_LOGIN = 'SOCIAL_LOGIN';

export const TOKEN = "TOKEN";

export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE'

export const CHANGE_MAIL_REQUEST = 'CHANGE_MAIL_REQUEST';
export const CHANGE_MAIL_SUCCESS = 'CHANGE_MAIL_SUCCESS';
export const CHANGE_MAIL_FAILURE = 'CHANGE_MAIL_FAILURE';

export const EDIT_CHANGE_MAIL_REQUEST = 'EDIT_CHANGE_MAIL_REQUEST'
export const EDIT_CHANGE_MAIL_SUCCESS = 'EDIT_CHANGE_MAIL_SUCCESS'
export const EDIT_CHANGE_MAIL_FAILURE = 'EDIT_CHANGE_MAIL_FAILURE'

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CHANGE_PASSWORD_FAILURE = 'CHANGE_PASSWORD_FAILURE';

export const EDIT_CHANGE_PASSWORD_REQUEST = 'EDIT_CHANGE_PASSWORD_REQUEST'
export const EDIT_CHANGE_PASSWORD_SUCCESS = 'EDIT_CHANGE_PASSWORD_SUCCESS'
export const EDIT_CHANGE_PASSWORD_FAILURE = 'EDIT_CHANGE_PASSWORD_FAILURE'

export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
